### ISSUE TITLE
[Bug]: Running the /start command in the development version reports an error

### ISSUE THREAD

**Issue by HelplessMan** [telegram-bot-sdk/telegram-bot-sdk#78]
### PHP version

8.1.8

### Telegram Bot SDK version

4.X

### Laravel version (if any)

v10.9.0

### What happened?

Install the dev version sdk, when executing the /start command, the log records the non-existent getMessage method, and the HelpCommand command does not have this problem

In the 4.x version of the SDK, how should I name the Command? For example: Index or IndexCommand? Does the above error have something to do with the name of the file?

```
local.ERROR: Method Illuminate\Support\Collection::getMessage does not exist. {"exception":"[object] (Telegram\\Bot\\Laravel\\Exceptions\\WebhookException(code: 0): Method Illuminate\\Support\\Collection::getMessage does not exist. 
```

### Code To Reproduce the bug

> Start.php

```
<?php

namespace App\Telegram\Commands;

use Telegram\Bot\Commands\Command;
use Throwable;

class Start extends Command
{
    protected string $description = 'Start command to process initial request!';

    /**
     * Execute the bot command.
     */
    public function handle()
    {
        $message = $this->getUpdate()->getMessage();
        $firstName = $message->from->first_name;

        $text = "Hello, $firstName! Welcome to our bot!\nType /help to get a list of available commands.";
        logger("firstName:" . $firstName);
        $this->bot->sendMessage([
            'chat_id' => $message->chat->id,
            'text' => $text,
        ]);
    }

    /**
     * Triggered on failure.
     */
    public function failed(array $arguments, Throwable $exception): void
    {
        //
    }
}

```

### Error stacktrace (if any)

```shell
[2023-05-08 08:23:51] local.ERROR: Method Illuminate\Support\Collection::getMessage does not exist. {"exception":"[object] (Telegram\\Bot\\Laravel\\Exceptions\\WebhookException(code: 0): Method Illuminate\\Support\\Collection::getMessage does not exist. at /data/www/telegram.chat.com/vendor/telegram-bot-sdk/laravel/src/Exceptions/WebhookException.php:12)
[stacktrace]
#0 /data/www/telegram.chat.com/vendor/telegram-bot-sdk/laravel/src/Http/Controllers/WebhookController.php(40): Telegram\\Bot\\Laravel\\Exceptions\\WebhookException::failedToListenToUpdate()
#1 /data/www/telegram.chat.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Telegram\\Bot\\Laravel\\Http\\Controllers\\WebhookController::Telegram\\Bot\\Laravel\\Http\\Controllers\\{closure}()
#2 /data/www/telegram.chat.com/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#3 /data/www/telegram.chat.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(81): Illuminate\\Container\\Util::unwrapIfClosure()
#4 /data/www/telegram.chat.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#5 /data/www/telegram.chat.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#6 /data/www/telegram.chat.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1250): Illuminate\\Container\\Container->call()
#7 /data/www/telegram.chat.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(215): Illuminate\\Foundation\\Application->terminate()
#8 /data/www/telegram.chat.com/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->terminate()
#9 {main}

[previous exception] [object] (BadMethodCallException(code: 0): Method Illuminate\\Support\\Collection::getMessage does not exist. at /data/www/telegram.chat.com/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php:113)
[stacktrace]
#0 /data/www/telegram.chat.com/vendor/telegram-bot-sdk/telegram-bot-sdk/src/Traits/ForwardsCalls.php(13): Illuminate\\Support\\Collection->__call()
#1 /data/www/telegram.chat.com/vendor/telegram-bot-sdk/telegram-bot-sdk/src/Objects/AbstractObject.php(69): Telegram\\Bot\\Objects\\AbstractObject->forwardCallTo()
#2 /data/www/telegram.chat.com/app/Telegram/Commands/Start.php(17): Telegram\\Bot\\Objects\\AbstractObject->__call()
#3 /data/www/telegram.chat.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Telegram\\Commands\\Start->handle()
#4 /data/www/telegram.chat.com/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#5 /data/www/telegram.chat.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#6 /data/www/telegram.chat.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#7 /data/www/telegram.chat.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#8 /data/www/telegram.chat.com/vendor/telegram-bot-sdk/telegram-bot-sdk/src/Commands/CommandBus.php(172): Illuminate\\Container\\Container->call()
#9 /data/www/telegram.chat.com/vendor/telegram-bot-sdk/telegram-bot-sdk/src/Commands/CommandBus.php(132): Telegram\\Bot\\Commands\\CommandBus->execute()
#10 /data/www/telegram.chat.com/vendor/telegram-bot-sdk/telegram-bot-sdk/src/Commands/CommandBus.php(113): Telegram\\Bot\\Commands\\CommandBus->process()
#11 /data/www/telegram.chat.com/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(236): Telegram\\Bot\\Commands\\CommandBus->Telegram\\Bot\\Commands\\{closure}()
#12 /data/www/telegram.chat.com/vendor/telegram-bot-sdk/telegram-bot-sdk/src/Commands/CommandBus.php(113): Illuminate\\Support\\Collection->each()
#13 /data/www/telegram.chat.com/vendor/telegram-bot-sdk/telegram-bot-sdk/src/Commands/CommandHandler.php(63): Telegram\\Bot\\Commands\\CommandBus->handler()
#14 /data/www/telegram.chat.com/vendor/telegram-bot-sdk/telegram-bot-sdk/src/Commands/Listeners/ProcessCommand.php(16): Telegram\\Bot\\Commands\\CommandHandler->processCommand()
#15 /data/www/telegram.chat.com/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(441): Telegram\\Bot\\Commands\\Listeners\\ProcessCommand->handle()
#16 /data/www/telegram.chat.com/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#17 /data/www/telegram.chat.com/vendor/telegram-bot-sdk/telegram-bot-sdk/src/Events/EventFactory.php(76): Illuminate\\Events\\Dispatcher->dispatch()
#18 /data/www/telegram.chat.com/vendor/telegram-bot-sdk/telegram-bot-sdk/src/Bot.php(186): Telegram\\Bot\\Events\\EventFactory->dispatch()
#19 /data/www/telegram.chat.com/vendor/telegram-bot-sdk/telegram-bot-sdk/src/Bot.php(150): Telegram\\Bot\\Bot->dispatchUpdateEvent()
#20 /data/www/telegram.chat.com/vendor/telegram-bot-sdk/telegram-bot-sdk/src/Bot.php(140): Telegram\\Bot\\Bot->useWebHook()
#21 /data/www/telegram.chat.com/vendor/telegram-bot-sdk/laravel/src/Http/Controllers/WebhookController.php(30): Telegram\\Bot\\Bot->listen()
#22 /data/www/telegram.chat.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Telegram\\Bot\\Laravel\\Http\\Controllers\\WebhookController::Telegram\\Bot\\Laravel\\Http\\Controllers\\{closure}()
#23 /data/www/telegram.chat.com/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#24 /data/www/telegram.chat.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(81): Illuminate\\Container\\Util::unwrapIfClosure()
#25 /data/www/telegram.chat.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#26 /data/www/telegram.chat.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#27 /data/www/telegram.chat.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1250): Illuminate\\Container\\Container->call()
#28 /data/www/telegram.chat.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(215): Illuminate\\Foundation\\Application->terminate()
#29 /data/www/telegram.chat.com/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->terminate()
#30 {main}
"}
```

**Comment by irazasyed** [comment]
In 4.x, You register commands in `name => commandClass` format in your config file.

The `name` is your command, so in this case it would be `/start` 

Example:

```php
// ...
'bots' => [
        'default' => [
            'token' => env('TELEGRAM_BOT_TOKEN', 'YOUR-BOT-TOKEN'),

            'commands' => [
                'start' => App\Telegram\Commands\Start::class,
            ],
	]
]
// ...
```

Accessing messages or any data is now done in either Object or Array syntax but you no longer have to prefix it with the `get` or call it as a method.

Example:

```php
// valid
$message = $this->getUpdate()->message;

// or
$message = $this->getUpdate()['message'];

**Comment by HelplessMan** [comment]
> `name => commandClass`在 4.x 中，您可以在配置文件中以格式注册命令。
> 
> 这`name`是你的命令，所以在这种情况下它会是`/start`
> 
> 例子：
> 
> ```
> // ...
> 'bots' => [
> 	'default' => [
>             'token' => env('TELEGRAM_BOT_TOKEN', 'YOUR-BOT-TOKEN'),
> 
>             'commands' => [
>                 'start' => App\Telegram\Commands\Start::class,
>             ],
> 	]
> ]
> // ...
> ```
> 
> 现在可以通过对象或数组语法访问消息或任何数据，但您不再需要在其前面加上前缀`get`或将其作为方法调用。
> 
> 例子：
> 
> ```
> // valid
> $message = $this->getUpdate()->message;
> 
> // or
> $message = $this->getUpdate()['message'];
> ```


Thank you,
Just now, after I updated the SDK, an error occurred when setting up WebHook!

```
Setting webhook for [default] bot!
Telegram\Bot\Api::setWebhook(): Return value must be of type bool, Telegram\Bot\Objects\ResponseObject returned
```
