### ISSUE TITLE
[Bug]: Call to undefined function GuzzleHttp\Promise\unwrap()

### ISSUE THREAD

**Issue by Ricardoooo0** [telegram-bot-sdk/telegram-bot-sdk#97]
### PHP version

8.2.4

### Telegram Bot SDK version

v3.9

### Laravel version (if any)

v8.83.27

### What happened?

my server code
```
private function __construct()
    {
        $this->bot = new Api(env('TELEGRAM_BOT_TOKEN'));
        $response = $this->bot->getMe();
    }
```
it throw 
```
Call to undefined function GuzzleHttp\Promise\unwrap() in file /private/var/www/domain-management/vendor/irazasyed/telegram-bot-sdk/src/HttpClients/GuzzleHttpClient.php on line 50
```

### Code To Reproduce the bug

```
class TgMsgService
{
    protected $bot;

    private static $instance;

    private function __construct()
    {
        $this->bot = new Api(env('TELEGRAM_BOT_TOKEN'));
        $response = $this->bot->getMe();
    }

    public static function getInstance()
    {
        if (empty(self::$instance)) {
            self::$instance = new self();
        }
        return self::$instance;
    }
}
```

### Error stacktrace (if any)

```shell
Error: Call to undefined function GuzzleHttp\Promise\unwrap() in file /private/var/www/domain-management/vendor/irazasyed/telegram-bot-sdk/src/HttpClients/GuzzleHttpClient.php on line 50

#0 /private/var/www/domain-management/app/Service/TgMsgService.php(21): Telegram\Bot\HttpClients\GuzzleHttpClient->__destruct()
#1 /private/var/www/domain-management/app/Http/Controllers/AgentHostController.php(1494): App\Service\TgMsgService::getInstance()
#2 /private/var/www/domain-management/app/Http/Controllers/AgentHostController.php(1434): App\Http\Controllers\AgentHostController->makeReport('\xE4\xBB\xA3\xE7\x90\x86\xE5\x9F\x9F\xE5\x90\x8D', '1299', 'admin', '\xE6\x9C\x89\xE9\x97\xAE\xE9\xA2\x98\xE5\x95\x8A', NULL, '92.118.204.131')
#3 /private/var/www/domain-management/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\AgentHostController->unhealthReport(Object(Illuminate\Http\Request))
#4 /private/var/www/domain-management/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('unhealthReport', Array)
#5 /private/var/www/domain-management/vendor/laravel/framework/src/Illuminate/Routing/Route.php(261): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\AgentHostController), 'unhealthReport')
#6 /private/var/www/domain-management/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route->runController()
#7 /private/var/www/domain-management/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\Routing\Route->run()
#8 /private/var/www/domain-management/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 /private/var/www/domain-management/app/Http/Middleware/checkBackendToken.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#10 /private/var/www/domain-management/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\checkBackendToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 /private/var/www/domain-management/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#12 /private/var/www/domain-management/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#13 /private/var/www/domain-management/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(127): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 /private/var/www/domain-management/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(93): Illuminate\Routing\Middleware\ThrottleRequests->handleRequest(Object(Illuminate\Http\Request), Object(Closure), Array)
#15 /private/var/www/domain-management/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(55): Illuminate\Routing\Middleware\ThrottleRequests->handleRequestUsingNamedLimiter(Object(Illuminate\Http\Request), Object(Closure), 'api', Object(Closure))
#16 /private/var/www/domain-management/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Routing\Middleware\ThrottleRequests->handle(Object(Illuminate\Http\Request), Object(Closure), 'api')
#17 /private/var/www/domain-management/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 /private/var/www/domain-management/vendor/laravel/framework/src/Illuminate/Routing/Router.php(719): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#19 /private/var/www/domain-management/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#20 /private/var/www/domain-management/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#21 /private/var/www/domain-management/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#22 /private/var/www/domain-management/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#23 /private/var/www/domain-management/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#24 /private/var/www/domain-management/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /private/var/www/domain-management/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /private/var/www/domain-management/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /private/var/www/domain-management/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /private/var/www/domain-management/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /private/var/www/domain-management/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TrimStrings->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /private/var/www/domain-management/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /private/var/www/domain-management/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /private/var/www/domain-management/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /private/var/www/domain-management/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /private/var/www/domain-management/vendor/fruitcake/laravel-cors/src/HandleCors.php(52): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /private/var/www/domain-management/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /private/var/www/domain-management/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /private/var/www/domain-management/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Http\Middleware\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /private/var/www/domain-management/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /private/var/www/domain-management/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#40 /private/var/www/domain-management/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#41 /private/var/www/domain-management/public/index.php(51): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#42 /private/var/www/domain-management/server.php(21): require_once('/private/var/ww...')
#43 {main}
```

**Comment by yi4396** [comment]
My PHP version is `7.4.33`, `telegram-bot-sdk` version is `3.9`, Temporary solution:   add `"guzzlehttp/promises": "^1.5"` to`composer.json`. The reason for the problem is that the promises 2.X version deprecates the `unwarp` method. 
Another way change vendor file: https://github.com/irazasyed/telegram-bot-sdk/issues/1086#issuecomment-1693234180
